-- MySQL Script generated by MySQL Workbench
-- Sat May 23 20:45:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fanatics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fanatics` ;

-- -----------------------------------------------------
-- Schema fanatics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fanatics` DEFAULT CHARACTER SET utf8 ;
USE `fanatics` ;

-- -----------------------------------------------------
-- Table `fanatics`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fanatics`.`usuario` ;

CREATE TABLE IF NOT EXISTS `fanatics`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `celular` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(255) NULL,
  `ativo` CHAR(1) NULL DEFAULT 'S',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fanatics`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fanatics`.`categoria` ;

CREATE TABLE IF NOT EXISTS `fanatics`.`categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fanatics`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fanatics`.`blog` ;

CREATE TABLE IF NOT EXISTS `fanatics`.`blog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `texto` VARCHAR(1000) NULL,
  `imagem` VARCHAR(45) NULL,
  `fk_usuario` INT NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_usuario1_idx` (`fk_usuario` ASC),
  INDEX `fk_blog_categoria1_idx` (`fk_categoria` ASC),
  CONSTRAINT `fk_blog_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `fanatics`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_categoria1`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `fanatics`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fanatics`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fanatics`.`equipe` ;

CREATE TABLE IF NOT EXISTS `fanatics`.`equipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `termos` CHAR(1) NOT NULL COMMENT '\'S\' = Aceito \'N\' = negado',
  `logo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fanatics`.`jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fanatics`.`jogador` ;

CREATE TABLE IF NOT EXISTS `fanatics`.`jogador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `nick` VARCHAR(70) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(20) NULL,
  `tipo` VARCHAR(45) NULL,
  `fk_equipe` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jogador_equipe1_idx` (`fk_equipe` ASC),
  CONSTRAINT `fk_jogador_equipe1`
    FOREIGN KEY (`fk_equipe`)
    REFERENCES `fanatics`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
